export const roomInclusions = {
  Standard: {
    threeto7Inclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: false },
      { label: '10+ Acupuncture treatments', available: false },
      { label: 'Private yoga sessions', available: false },
      { label: 'Modern detoxification treatments', available: false },
      { label: 'Transportation services', available: false },
    ],
    eightPlusInclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: false },
      { label: '10+ Acupuncture treatments', available: false },
      { label: 'Private yoga sessions', available: false },
      { label: 'Modern detoxification treatments', available: false },
      { label: 'Transportation services', available: false },
    ],
  },
  'Premium Balcony': {
    threeto7Inclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: false },
      { label: '10+ Acupuncture treatments', available: false },
      { label: 'Private yoga sessions', available: false },
      { label: 'Modern detoxification treatments', available: false },
      { label: 'Transportation services', available: false },
    ],
    eightPlusInclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: false },
      { label: '10+ Acupuncture treatments', available: false },
      { label: 'Private yoga sessions', available: false },
      { label: 'Modern detoxification treatments', available: false },
      { label: 'Transportation services', available: false },
    ],
  },

  'Premium Garden': {
    threeto7Inclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: false },
      { label: '10+ Acupuncture treatments', available: false },
      { label: 'Private yoga sessions', available: false },
      { label: 'Modern detoxification treatments', available: false },
      { label: 'Transportation services', available: false },
    ],
    eightPlusInclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: false },
      { label: '10+ Acupuncture treatments', available: false },
      { label: 'Private yoga sessions', available: false },
      { label: 'Modern detoxification treatments', available: false },
      { label: 'Transportation services', available: false },
    ],
  },

  Executive: {
    threeto7Inclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: false },
      { label: '10+ Acupuncture treatments', available: false },
      { label: 'Private yoga sessions', available: false },
      { label: 'Modern detoxification treatments', available: false },
      { label: 'Transportation services', available: false },
    ],
    eightPlusInclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments (2 sessions)', available: true },
      { label: '10+ Acupuncture treatments (2 sessions)', available: true },
      { label: 'Private yoga sessions (2 sessions)', available: true },
      { label: 'Modern detoxification treatments (2 sessions)', available: true },
      { label: 'Transportation services', available: true },
    ],
  },
  'Executive Junior Suite': {
    threeto7Inclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: true },
      { label: '10+ Acupuncture treatments', available: true },
      { label: 'Private yoga sessions', available: true },
      { label: 'Modern detoxification treatments', available: true },
      { label: 'Transportation services', available: true },
    ],
    eightPlusInclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments ', available: true },
      { label: '10+ Acupuncture treatments ', available: true },
      { label: 'Private yoga sessions ', available: true },
      { label: 'Modern detoxification treatments ', available: true },
      { label: 'Transportation services', available: true },
    ],
  },
  'Garden Executive Suite': {
    threeto7Inclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: true },
      { label: '10+ Acupuncture treatments', available: true },
      { label: 'Private yoga sessions', available: true },
      { label: 'Modern detoxification treatments', available: true },
      { label: 'Transportation services', available: true },
    ],
    eightPlusInclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments ', available: true },
      { label: '10+ Acupuncture treatments ', available: true },
      { label: 'Private yoga sessions ', available: true },
      { label: 'Modern detoxification treatments ', available: true },
      { label: 'Transportation services', available: true },
    ],
  },

  'Pema Suite': {
    threeto7Inclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: true },
      { label: '10+ Acupuncture treatments', available: true },
      { label: 'Private yoga sessions', available: true },
      { label: 'Modern detoxification treatments', available: true },
      { label: 'Transportation services', available: true },
    ],
    eightPlusInclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: true },
      { label: '10+ Acupuncture treatments', available: true },
      { label: 'Private yoga sessions', available: true },
      { label: 'Modern detoxification treatments', available: true },
      { label: 'Transportation services', available: true },
    ],
  },

  'Elemental Villa': {
    threeto7Inclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: true },
      { label: '10+ Acupuncture treatments', available: true },
      { label: 'Private yoga sessions', available: true },
      { label: 'Modern detoxification treatments', available: true },
      { label: 'Transportation services', available: true },
    ],
    eightPlusInclusions: [
      { label: 'Naturopathic cuisine', available: true },
      { label: 'Daily doctor consultations', available: true },
      { label: 'Guided group wellness activities (Yoga, Meditation & movement)', available: true },
      { label: '55+ Manipulative & hydro-therapies', available: true },
      { label: '40+ Fomentations, wraps & packs', available: true },
      { label: '20+ Physiotherapy treatments', available: true },
      { label: '10+ Acupuncture treatments', available: true },
      { label: 'Private yoga sessions', available: true },
      { label: 'Modern detoxification treatments', available: true },
      { label: 'Transportation services', available: true },
    ],
  },
}
