"""Add booking_details to payments table

Revision ID: 010ba7636538
Revises: 
Create Date: 2025-10-30 23:24:31.975294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010ba7636538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
